### ISSUE TITLE
KeyError, 62 failed tests

### ISSUE THREAD

**Issue by falbanese90** [jjotterson/datapungi_fed#2]
I'm wondering if someone can help with this..
I've been getting KeyErrors anytime I try to run the data function.

I ran the test and it failed 62 times, all indicating KeyErrors within the cleanOutput function.

Any suggestions would be much appreciated..
<img width="752" alt="Screen Shot 2021-01-24 at 12 18 08 PM" src="https://user-images.githubusercontent.com/77649129/105637976-3f6ca480-5e3e-11eb-9187-f3e253500407.png">
<img width="581" alt="Screen Shot 2021-01-24 at 12 17 53 PM" src="https://user-images.githubusercontent.com/77649129/105637978-43002b80-5e3e-11eb-97ad-9b233328b096.png">

**Comment by falbanese90** [comment]
It was an issue with the program not getting access to the api key from the bash_profile..fixed by passing the key manually..

**Comment by jjotterson** [comment]
were you saving the key as an environment variable? Re-starting the terminal may help with this.

**Comment by falbanese90** [comment]
Yes, I also restarted the computer..couldn’t get it to populate.

**Comment by jjotterson** [comment]
are you using mac or pc?
